// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmvraufedpuzqokgiuaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdnJhdWZlZHB1enFva2dpdWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzQxMDYsImV4cCI6MjA1ODQ1MDEwNn0.FgfGp6UpXDfDtF2XcyAbk3pOly3pNSUx1ErwuYvApgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);